# Reference from: http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
version: '2.1'
services: 
    mysql:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        volumes:
            - mysqldb_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=SuperSecret
            - MYSQL_DATABASE=magento
            - MYSQL_USER=magento
            - MYSQL_PASSWORD=magento
        healthcheck:
            test: mysql --user=root --password=SuperSecret -e 'SELECT * FROM INFORMATION_SCHEMA.TABLES;'
            timeout: 20s
            retries: 10
    php:
        image: 'b2b_magento2/php'
        build:
            context: ./php
        environment:
            - M2SETUP_DB_HOST=mysql
            - M2SETUP_DB_NAME=magento
            - M2SETUP_DB_USER=magento
            - M2SETUP_DB_PASSWORD=magento
            - M2SETUP_BASE_URL=http://localhost/
            - M2SETUP_ADMIN_FIRSTNAME=Admin
            - M2SETUP_ADMIN_LASTNAME=User
            - M2SETUP_ADMIN_EMAIL=admin@user.com
            - M2SETUP_ADMIN_USER=magento2
            - M2SETUP_ADMIN_PASSWORD=magento2
            - M2SETUP_ADMIN_URI=admin
            - M2SETUP_USE_SAMPLE_DATA=false
            - M2SETUP_FORCE_EXECUTION=true
            - M2MODE=developer
        volumes:
            - ~/.composer/auth.json:/root/.composer/auth.json
        depends_on:
            "mysql":
                condition: service_healthy
    nginx:
        image: 'b2b_magento2/nginx'
        build:
            context: ./nginx
        ports:
            - '80:80'
        environment:
            - NGINX_SERVER_NAME=localhost
        volumes_from:
            - php:ro
        depends_on:
            "php":
                 condition: service_started
volumes:
  mysqldb_data:
