# Reference from: http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
version: '2.1'
services: 
    nginx:
        image: 'nginx:latest'
        ports:
            - '80:80'
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: 'dirceu/php'
        build:
            context: ./php
        volumes:
            - ./code:/code
    mysql:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        volumes:
            - mysqldb_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=SuperSecret
volumes:
  mysqldb_data:
